import { Addendum } from "./schema";

export const adddendumsList: Addendum[] = [
  {
    id: "1",
    number: "0001",
    description: "Update Quatation scope",
    contractNumber: "AE/0023/2022-2023/0001",
    contractDescription: "Supply of Kycera",
    statusCode: "DRAFT",
    statusName: "Draft",
    submittedBy: "Silvester Ntunga",
    reviewedBy: "Silvester Ntunga",
    reviewerComment: "Proceed as requested",
    approverComment: "Proceed as requested",
    approvedBy: "Silvester Ntunga",
    submittedDate: "01 January 2023 10:11",
    reviewedDate: "01 January 2023 10:11",
    approvedDate: "01 January 2023 10:11",
  },
  {
    id: "2",
    number: "0002",
    description: "Update Quatation scope",
    contractNumber: "AE/0023/2022-2023/0001",
    contractDescription: "Supply of Kycera",
    statusCode: "SUBMITTED",
    statusName: "Submitted",
    submittedBy: "Silvester Ntunga",
    reviewedBy: "Silvester Ntunga",
    approvedBy: "Silvester Ntunga",
    reviewerComment: "Proceed as requested",
    approverComment: "Proceed as requested",
    submittedDate: "01 January 2023 10:11",
    reviewedDate: "01 January 2023 10:11",
    approvedDate: "01 January 2023 10:11",
  },
  {
    id: "3",
    number: "0003",
    description: "Update Quatation scope",
    contractNumber: "AE/0023/2022-2023/0001",
    contractDescription: "Supply of Kycera",
    statusCode: "APPROVED",
    statusName: "Approved",
    submittedBy: "Silvester Ntunga",
    reviewedBy: "Silvester Ntunga",
    approvedBy: "Silvester Ntunga",
    reviewerComment: "Proceed as requested",
    approverComment: "Proceed as requested",
    submittedDate: "01 January 2023 10:11",
    reviewedDate: "01 January 2023 10:11",
    approvedDate: "01 January 2023 10:11",
  },
];
